name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Minecraft-Exporter:$(date +%s)

    - name: Log in to Docker Hub  
      uses: docker/login-action@v1  
      with:  
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Build the Docker image  
      uses: docker/build-push-action@v2  
      with:  
        context: .  
        file: ./Dockerfile  
        push: true  
        tags: yiyuanzhao/minecraft-exporter:latest
